# Generated by Django 3.1.3 on 2023-02-24 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default=' ')),
                ('estudio', models.TextField(default=' ')),
                ('genero', models.TextField(default=' ')),
                ('anio', models.DateField(default=django.utils.timezone.now)),
                ('duracion', models.IntegerField(default=90)),
                ('recaudacion', models.FloatField(default=0)),
                ('director', models.TextField(default=' ')),
                ('productor', models.TextField(default=' ')),
                ('valoracion', models.IntegerField(default=0)),
                ('servicio', models.IntegerField(default=0)),
            ],
        ),
    ]
