# Generated by Django 3.1.3 on 2023-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20230224_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='servicio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
