# Generated by Django 3.1.3 on 2023-05-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20230224_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
    ]
