# Generated by Django 3.1.3 on 2023-05-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_pelicula_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='comentarios',
        ),
    ]
