# Generated by Django 3.1.3 on 2023-05-27 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='link',
        ),
        migrations.AddField(
            model_name='vote',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='peliculas.pelicula'),
        ),
    ]
