apiVersion: v1
kind: ConfigMap
metadata:
 name: lokenmg-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: 'esta_caliente_y_no_hay_hielo'
 DEV_DATABASE: 'xhfzaega'
 DEV_USER: 'xhfzaega'
 DEV_PASSWORD: 'ICYhxHYhlQDb6sjlpM8ONOzmNaX5_rQg'
 DEV_HOST: 'mahmud.db.elephantsql.com'
 DEV_PORT: "5432"
 
 PROD_SECRET_KEY: 'esta_caliente_y_no_hay_hielo'
 PROD_DATABASE: 'xhfzaega'
 PROD_USER: 'xhfzaega'
 PROD_PASSWORD: 'ICYhxHYhlQDb6sjlpM8ONOzmNaX5_rQg'
 PROD_HOST: 'mahmud.db.elephantsql.com'
 PROD_PORT: "5432"
