name: release CI/CD

#Conrols when the action will run
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
    
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: show linux version
      run: lsb_release -a
    - name: show archives
      run: ls -la
    - name: python version
      run: python --version
    - name: runserver
      run: python manage.py runserver --settings=settings.local
